### ISSUE TITLE
Two `action` keys in one "Perform Action“ obs filter?

### ISSUE THREAD

**Issue by guoqing-noaa** [NOAA-EMC/RDASApp#303]
https://github.com/NOAA-EMC/RDASApp/blob/6f5ac85797814983ac405b2bd6ad616a2ead65e2/rrfs-test/validated_yamls/templates/obtype_config/aircar_airTemperature_133.yaml#L60

Here we have two actions:

![Image](https://github.com/user-attachments/assets/e0e5d700-4efa-45a7-a47a-130aa8e3555f)

For YAML itself, the second one will overwrite the first one. I don't know how JEDI handle this situation.

**Comment by guoqing-noaa** [comment]
@SamuelDegelia-NOAA @spanNOAA @delippi

**Comment by delippi** [comment]
I will double check how this is handled in JEDI

**Comment by SamuelDegelia-NOAA** [comment]
It would probably be cleaner to keep both actions under the same key, but I think this style is still working correctly. I tested a few different configurations just now with the above QualityMarker filter for `aircar_airTemperature_133.yaml`. 

```
action:
  name: reject
Result nobs = 35767
```

```
action:
  name: reject
action:
  name: reduce obs space
Result nobs = 34019
```

```
action:
  name: reject
  name: reduce obs space
Result nobs = 34019
```

Note that listing `reduce obs space` first does not work since the `reject` action hasn't occurred yet: 

```
action:
  name: reduce obs space
  name: reject
Result nobs = 35767
```
