### ISSUE TITLE
Can we mimic the offline domain check using a lat/lon box domain check filter?

### ISSUE THREAD

**Issue by guoqing-noaa** [NOAA-EMC/RDASApp#315]
We may use a lat/lat box which just encloses our model domain to remove most outside observations in the pre filter, something as follows:
```
filter: Domain Check
where:
- variable:
    name: MetaData/latitude
  minvalue: -9.06518
  maxvalue: 11.4725
- variable:
    name: MetaData/longitude
  minvalue: 91.7506
  maxvalue: 112.268
action:
  name: reduce obs space
```
Will this have the potential to replace the offline domain check capability in RDASApp? Can this address the problem you met? @SamuelDegelia-NOAA

**Comment by SamuelDegelia-NOAA** [comment]
@guoqing-noaa Yes this has been our thought for a bit on how to replace the offline domain check. We would use this domain check pre-filter with `reduce obs space` to remove most obs from memory that are outside the domain. Then the would also call the online domain check (prior filter) to QC out (but not remove from memory) any obs left over that the first domain check did not catch. 

@HuiLiu-NOAA has implemented this idea for his ZTD yaml in #299. 

I have had this on my to do list to test for all obs types but have not gotten around to it. But this is the general idea.

**Comment by guoqing-noaa** [comment]
Great to hear it will work, and @HuiLiu-NOAA has implemented it in the ZTD yaml.

**Comment by guoqing-noaa** [comment]
@SamuelDegelia-NOAA @HuiLiu-NOAA Can we apply `domain check` to a given variable, like temperature?  I am asking this because it looks like we can use `domain check` to keep only qcflags between 0-3 like this:
```
filter: Domain Check
where:
- variable:
    name: QualityMarker/airTemperature
  minvalue: 0
  maxvalue: 3
action:
  name: reduce obs space
```

Or in RDASApp, each observer corresponds to only one type of observations, such as t133, uv133, q133, so even we cannot apply `domain check` to a given variable, we can still use it without a problem?
